# Generated by Django 4.2.6 on 2023-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='github_link2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
